export const STANDARD_TIMEZONES = [
    // UTC Minus
    { label: "Anywhere on Earth (AoE) (UTC-12:00)", zone: "Etc/GMT+12" },
    { label: "Niue Time (NUT) (UTC-11:00)", zone: "Pacific/Niue" },
    { label: "Samoa Standard Time (SST) (UTC-11:00)", zone: "Pacific/Pago_Pago" },
    { label: "Hawaii-Aleutian Standard Time (HST) (UTC-10:00)", zone: "Pacific/Honolulu" },
    { label: "Tahiti Time (UTC-10:00)", zone: "Pacific/Tahiti" },
    { label: "Marquesas Islands Time (MART) (UTC-09:30)", zone: "Pacific/Marquesas" },
    { label: "Alaska Standard Time (AKST) (UTC-09:00)", zone: "America/Anchorage" },
    { label: "Gambier Time (GAMT) (UTC-09:00)", zone: "Pacific/Gambier" },
    { label: "Pacific Standard Time (PST) (UTC-08:00)", zone: "America/Los_Angeles" },
    { label: "Mountain Standard Time (MST) (UTC-07:00)", zone: "America/Denver" },
    { label: "Central Standard Time (CST) (UTC-06:00)", zone: "America/Chicago" },
    { label: "Galapagos Time (GALT) (UTC-06:00)", zone: "Pacific/Galapagos" },
    { label: "Eastern Standard Time (EST) (UTC-05:00)", zone: "America/New_York" },
    { label: "Colombia Time (COT) (UTC-05:00)", zone: "America/Bogota" },
    { label: "Peru Time (PET) (UTC-05:00)", zone: "America/Lima" },
    { label: "Venezuela Time (VET) (UTC-04:00)", zone: "America/Caracas" },
    { label: "Atlantic Standard Time (AST) (UTC-04:00)", zone: "America/Halifax" },
    { label: "Bolivia Time (BOT) (UTC-04:00)", zone: "America/La_Paz" },
    { label: "Newfoundland Standard Time (NST) (UTC-03:30)", zone: "America/St_Johns" },
    { label: "Argentina Time (ART) (UTC-03:00)", zone: "America/Argentina/Buenos_Aires" },
    { label: "Brasilia Time (BRT) (UTC-03:00)", zone: "America/Sao_Paulo" },
    { label: "South Georgia Time (GST) (UTC-02:00)", zone: "Etc/GMT+2" },
    { label: "Azores Standard Time (AZOT) (UTC-01:00)", zone: "Atlantic/Azores" },
    { label: "Cape Verde Time (CVT) (UTC-01:00)", zone: "Atlantic/Cape_Verde" },

    // UTC Baseline
    { label: "Greenwich Mean Time (GMT) (UTC+00:00)", zone: "Etc/GMT" },
    { label: "Western European Time (WET) (UTC+00:00)", zone: "Europe/London" },

    // UTC Plus
    { label: "Central European Time (CET) (UTC+01:00)", zone: "Europe/Paris" },
    { label: "Eastern European Time (EET) (UTC+02:00)", zone: "Europe/Athens" },
    { label: "South Africa Standard Time (SAST) (UTC+02:00)", zone: "Africa/Johannesburg" },
    { label: "East Africa Time (EAT) (UTC+03:00)", zone: "Africa/Nairobi" },
    { label: "Moscow Time (MSK) (UTC+03:00)", zone: "Europe/Moscow" },
    { label: "Arabia Standard Time (AST) (UTC+03:00)", zone: "Asia/Riyadh" },
    { label: "Iran Standard Time (IRST) (UTC+03:30)", zone: "Asia/Tehran" },
    { label: "Gulf Standard Time (GST) (UTC+04:00)", zone: "Asia/Dubai" },
    { label: "Afghanistan Time (AFT) (UTC+04:30)", zone: "Asia/Kabul" },
    { label: "Pakistan Standard Time (PKT) (UTC+05:00)", zone: "Asia/Karachi" },
    { label: "Indian Standard Time (IST) (UTC+05:30)", zone: "Asia/Kolkata" },
    { label: "Nepal Time (NPT) (UTC+05:45)", zone: "Asia/Kathmandu" },
    { label: "Bangladesh Standard Time (BST) (UTC+06:00)", zone: "Asia/Dhaka" },
    { label: "Myanmar Standard Time (MMT) (UTC+06:30)", zone: "Asia/Yangon" },
    { label: "Indochina Time (ICT) (UTC+07:00)", zone: "Asia/Bangkok" },
    { label: "China Standard Time (CST) (UTC+08:00)", zone: "Asia/Shanghai" },
    { label: "Singapore Standard Time (SGT) (UTC+08:00)", zone: "Asia/Singapore" },
    { label: "Japan Standard Time (JST) (UTC+09:00)", zone: "Asia/Tokyo" },
    { label: "Korea Standard Time (KST) (UTC+09:00)", zone: "Asia/Seoul" },
    { label: "Australian Central Standard Time (ACST) (UTC+09:30)", zone: "Australia/Darwin" },
    { label: "Australian Eastern Standard Time (AEST) (UTC+10:00)", zone: "Australia/Sydney" },
    { label: "New Zealand Standard Time (NZST) (UTC+12:00)", zone: "Pacific/Auckland" },
    { label: "Fiji Time (FJT) (UTC+12:00)", zone: "Pacific/Fiji" },
    { label: "Tonga Time (TOT) (UTC+13:00)", zone: "Pacific/Tongatapu" },
    { label: "Line Islands Time (UTC+14:00)", zone: "Pacific/Kiritimati" }
];
